# Importing numpy as np
#### As we always wanted to call the module again and again we can call it simple as np instead of numpy

In [1]:
import numpy as np

##### creating numpy array using `np.array()`

In [2]:
arr_one = np.array([1,2,3,4,5,6])
arr_one

array([1, 2, 3, 4, 5, 6])

##### creating two dimension array


In [3]:
arr_two= np.array([[1,2,3,4],[5,6,7,8]])
arr_two

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##### Here we can see the difference between numpy array and python lists

In [4]:
list1 = list(range(1000000))

In [5]:
list2 = np.arange(1000000)

In [6]:
%time for _ in range(10):list2_1 = list2 * 2

CPU times: total: 78.1 ms
Wall time: 57.6 ms


In [7]:
%time for _ in range(10):list1_1 = [x*2 for x in list1]

CPU times: total: 1.31 s
Wall time: 1.61 s


##### creating numpy arrays with all zeros filled using `np.zeros`

In [8]:
arr_zero = np.zeros(5)
arr_zero

array([0., 0., 0., 0., 0.])

##### creating numpy arrays with all ones filled using `np.ones`


In [9]:
arr_ones = np.ones(5)
arr_ones

array([1., 1., 1., 1., 1.])

##### we can use `np.zeros` and `np.ones` functions by passing shape of the array needed

In [10]:
arr_zeros_1 = np.zeros((3,4))
arr_ones_1 = np.ones((3,4))
arr_zeros_1, arr_ones_1

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

##### here these `np.zeros` and `np.ones` gives arrays in np.float data type
##### you can check the data type using `arr.dtype` where arr is the `np.array` or np object

In [11]:
arr_zeros_1.dtype,arr_ones_1.dtype

(dtype('float64'), dtype('float64'))

#### here we learn some basic numpy properties 
1. to see *size* of the numpy-array use `arr.size`

2. to see *shape* of the nu,py-array use `arr.shape`

3. to see *documentation* of any function in numpy library use `np.info`

4. to *convert* the numpy-array into python lists use `arr.tolist()`

5. to *convert* the type of numpy-arrray use `arr.astype(*dtype*)`

In [12]:
arr_two.size

8

In [13]:
arr_two.shape

(2, 4)

In [14]:
np.info(np.dtypes)

This module is home to specific dtypes related functionality and their classes.
For more general information about dtypes, also see `numpy.dtype` and
:ref:`arrays.dtypes`.

Similar to the builtin ``types`` module, this submodule defines types (classes)
that are not widely used directly.

.. versionadded:: NumPy 1.25

    The dtypes module is new in NumPy 1.25.  Previously DType classes were
    only accessible indirectly.


DType classes
-------------

The following are the classes of the corresponding NumPy dtype instances and
NumPy scalar types.  The classes can be used in ``isinstance`` checks and can
also be instantiated or used directly.  Direct use of these classes is not
typical, since their scalar counterparts (e.g. ``np.float64``) or strings
like ``"float64"`` can be used.


In [15]:
li = arr_two.tolist()
li

[[1, 2, 3, 4], [5, 6, 7, 8]]

##### now we check the `arr_two` dtype and convert it into float

In [16]:
arr_two.dtype

dtype('int64')

##### here the astype returns an numpy-array but it will not store the object itself

In [17]:
arr_two.astype(np.float64)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

##### only while using the astype it will give the array else the same data type will be there

In [18]:
arr_two.dtype

dtype('int64')

##### now let us look for another function same like `zeros`,`ones` that is `np.eye`

it gives an identity matrix that is it will give an n x n matrix with 1 on diagonals and 0 on other places


In [19]:
arr_eye = np.eye(5)
arr_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##### another function to create np-array is using `np.linspace` this creates the array from start to stop on giving divison length between them

In [20]:
arr_linspace = np.linspace(3,30,10)
arr_linspace

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

##### here the array dtype is `np.float64`

In [21]:
arr_linspace.dtype

dtype('float64')

##### Now another function to create numpy-array is `np.arange` it creates a range of values with a *start* , *stop* , *step* in it

In [22]:
arr_arange = np.arange(16,32)
arr_arange

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

##### the `np.arange` array shape is always 1-dim.

In [23]:
arr_arange.shape

(16,)

##### another function for creating np-arrays is `np.full` it can take the shape that needed to create and a value to fill the entire array with that

In [24]:
arr_full = np.full((3,4),5)
arr_full

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

##### another type to create a np-array is to use `np.random.rand`  
1. we can use it two type if we use `np.random.rand` directly it gives valuse in range between 0 and 1
2. if we use `np.random.rand()*100` it gives float between 0 and 100 

In [25]:
arr_rand = np.random.rand(3,4)
arr_rand

array([[0.21241761, 0.03119036, 0.84598315, 0.54570448],
       [0.19174378, 0.40206237, 0.75061872, 0.72687351],
       [0.31914302, 0.04934742, 0.89628785, 0.18925867]])

In [26]:
arr_rand_1 = np.random.rand(3,4)*100
arr_rand_1

array([[98.41408035, 97.43250204, 74.72804684,  6.46998553],
       [27.20835116, 66.89971225,  7.8214236 , 45.28438606],
       [80.11746709, 61.15010313, 65.5041801 , 34.64254412]])

##### the last function is `np.random.randint` which takes an integer number and a tuple of shape and it returns a random integer between given starting and stoping integer


In [27]:
arr_rand_int = np.random.randint(10,size=(3,4))
arr_rand_int

array([[3, 7, 5, 4],
       [8, 4, 3, 1],
       [8, 3, 8, 4]], dtype=int32)

##### Now let us see all listed np-array creation functions
1. `np.array`
2. `np.zeros`
3. `np.ones`
4. `np.eye`
5. `np.linspace`
6. `np.arange`
7. `np.full`
8. `np.random.rand`
9. `np.random.randint`

### Copying, sorting, & Reshaping


##### To copy the np-array we use `np.copy(arr)` function which copy the array into new memory

In [28]:
arr_two_copy = np.copy(arr_two)
arr_two_copy

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##### `np.copy(arr)` makes deep copy so any change in *arr* do not **replicate** in copied array

In [29]:
arr_two_copy[1,2] = 6
arr_two_copy

array([[1, 2, 3, 4],
       [5, 6, 6, 8]])

In [30]:
arr_two

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##### we can create a view for the given arr with different **dtype** using `arr.view(dtype)` or else we can leave empty to get same data type view

In [31]:
arr_two_view = arr_two.view()# use np.float64 as parameter to get difference
arr_two_view

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##### View can change values if the *original array* values are changed or **vice-verca**

In [32]:
arr_two_view[1,2] = 6
arr_two_view

array([[1, 2, 3, 4],
       [5, 6, 6, 8]])

In [33]:
arr_two

array([[1, 2, 3, 4],
       [5, 6, 6, 8]])

In [34]:
arr_two[1,2] = 7
arr_two

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
arr_two_view

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##### To sort an np-array we can use the np-array function *i.e* `arr.sort()`

In [36]:
arr_rand_int2 = np.random.randint(16,size=(4,4))
arr_rand_int2

array([[ 1,  4,  6, 13],
       [15,  0,  8,  8],
       [11,  9,  5, 10],
       [14, 11,  9, 14]], dtype=int32)

##### As this `arr_rand_int2` is not **1-D** array but it does sort the array for only one row means all elements in one row is sorted in the same row 

In [37]:
arr_rand_int2.sort()
arr_rand_int2

array([[ 1,  4,  6, 13],
       [ 0,  8,  8, 15],
       [ 5,  9, 10, 11],
       [ 9, 11, 14, 14]], dtype=int32)

##### Here we can also use parameter `arr.sort(axis)` where *axis = 0 or 1* 
1. axis = 0 represent to sort the values according to column wise means it sort all the column values
2. axis = 1 represent to sort the values according to row wise means it sort all the values in row

`arr.sort()` corresponds to `arr.sort(axis=1)`

In [38]:
arr_rand_int2.sort(axis=0)
arr_rand_int2

array([[ 0,  4,  6, 11],
       [ 1,  8,  8, 13],
       [ 5,  9, 10, 14],
       [ 9, 11, 14, 15]], dtype=int32)

##### To flatten an n-dim or any-shape np-array we use `arr.flatten()` it converts into 1-dim np.array and returns an 1-dim np.array

In [39]:
arr_rand_int2.flatten()

array([ 0,  4,  6, 11,  1,  8,  8, 13,  5,  9, 10, 14,  9, 11, 14, 15],
      dtype=int32)

##### To **Transpose** the np-arr i.e *rows* becoming *columns* and vice-verca we use `arr.T`

In [40]:
arr_rand_int2,arr_rand_int2.T

(array([[ 0,  4,  6, 11],
        [ 1,  8,  8, 13],
        [ 5,  9, 10, 14],
        [ 9, 11, 14, 15]], dtype=int32),
 array([[ 0,  1,  5,  9],
        [ 4,  8,  9, 11],
        [ 6,  8, 10, 14],
        [11, 13, 14, 15]], dtype=int32))

##### Reshaping an array using `arr.reshape(x,y)` that reshapes an array into x,y shape
Make sure to have **x*y** elements in the array to reshape correctly without any error

In [41]:
arr_rand_int2.reshape(2,8,order='F')

array([[ 0,  5,  4,  9,  6, 10, 11, 14],
       [ 1,  9,  8, 11,  8, 14, 13, 15]], dtype=int32)

##### Here we have two orders they are `'C'` and `'F'` 
`C` makes to reshape on the basis of row wise filling elements

`F` makes to reshape on the basis of column wise filling elements

##### Here `arr_rand_int2` is of shape **(4,4)** but after reshape you can see the output in shape of **(2,8)**

##### Now we get another np-array function that is `arr.resize((x,y))` this make an array to rershape to any size and it automatically fills the values to **0** that are not initialised

In [42]:
arr_arange.resize((2,8))
arr_arange

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

#### Adding & Removing Elements

##### To append the value to the end of np-array we use `np.append(arr,values)` 

In [43]:
arr_append = np.append(arr_one,[1,2,3,5])
arr_append

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 5])

##### To insert values in np-array we use `np.insert(arr,pos,values)`

In [44]:
arr_insert = np.insert(arr_two,1,[1,5,3,4],axis = 0)
arr_insert

array([[1, 2, 3, 4],
       [1, 5, 3, 4],
       [5, 6, 7, 8]])

##### To delete values in np-array we use `np.delete(arr,pos,axis)`

In [45]:
arr_delete = np.delete(arr_two,0,axis=0)
arr_delete

array([[5, 6, 7, 8]])

In [46]:
arr_delete = np.delete(arr_two,1,axis=1)
arr_delete

array([[1, 3, 4],
       [5, 7, 8]])

#### Combining and Splitting
##### to concatenate two np-arrays we use `np.concatenate((arr1,arr2),axis)`

In [47]:
arr_concatenate = np.concatenate((arr_rand_int2,arr_two),axis=0)
arr_concatenate

array([[ 0,  4,  6, 11],
       [ 1,  8,  8, 13],
       [ 5,  9, 10, 14],
       [ 9, 11, 14, 15],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [48]:
arr_concatenate = np.concatenate((arr_two,arr_two),axis=1)
arr_concatenate

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

##### To split an array we use `np.split(arr,value)` here value refers to how many array it needs to be split

In [49]:
arr_split = np.split(arr_rand_int2,4)
arr_split

[array([[ 0,  4,  6, 11]], dtype=int32),
 array([[ 1,  8,  8, 13]], dtype=int32),
 array([[ 5,  9, 10, 14]], dtype=int32),
 array([[ 9, 11, 14, 15]], dtype=int32)]

##### To Split np-array Horizontally we use `np.hsplit(arr,value)` it splits the arr horizontally

In [50]:
arr_hsplit = np.hsplit(arr_rand_int2,4)
arr_hsplit

[array([[0],
        [1],
        [5],
        [9]], dtype=int32),
 array([[ 4],
        [ 8],
        [ 9],
        [11]], dtype=int32),
 array([[ 6],
        [ 8],
        [10],
        [14]], dtype=int32),
 array([[11],
        [13],
        [14],
        [15]], dtype=int32)]

### Indexing & Slicing

##### Indexing with `[]` to get elements of the np-array

##### `arr[1]` gives element at position 1 respecting to shape of the np-arr

In [51]:
arr_rand_int2[1]

array([ 1,  8,  8, 13], dtype=int32)

##### `arr[1,2]` gives element of position `arr[1][2]` 

In [52]:
arr_rand_int2[1,2]

np.int32(8)

##### We can assign the values using `[]` like `arr[1] = 4 `

In [53]:
arr_rand_int2[1] = 4
arr_rand_int2

array([[ 0,  4,  6, 11],
       [ 4,  4,  4,  4],
       [ 5,  9, 10, 14],
       [ 9, 11, 14, 15]], dtype=int32)

##### Here something called broadcasting is applied in the above code. Broadcasting means some times the given number like above we give `4` value for `arr_rand_int2[1]` but it has an entire row so numpy directly make `4` as `[4,4,4,4]` matching the shape of the given np-array

##### We can also assign value to specific index like `arr[1,2] = 3`

In [54]:
arr_rand_int2[1,2] = 3
arr_rand_int2

array([[ 0,  4,  6, 11],
       [ 4,  4,  3,  4],
       [ 5,  9, 10, 14],
       [ 9, 11, 14, 15]], dtype=int32)

##### We can also slice the np-array as python list like `arr[1:3]` this returns the elements at index *1*,*2* 

In [55]:
arr_rand_int2[1:3]

array([[ 4,  4,  3,  4],
       [ 5,  9, 10, 14]], dtype=int32)

##### For multi dimension we can also specify element value to get like `arr[1:3,2]` this returns the elements at index *2* of rows *1*, *2*

In [56]:
arr_rand_int2[1:3,2]

array([ 3, 10], dtype=int32)

##### `arr[:2]` gives all indexes before index 2 i.e *0*, *1*

In [57]:
arr_rand_int2[:2]

array([[ 0,  4,  6, 11],
       [ 4,  4,  3,  4]], dtype=int32)

##### `arr[:,2]` gives all elements at index 2 from every row

In [58]:
arr_rand_int2[:,2]

array([ 6,  3, 10, 14], dtype=int32)

##### We can iterate through an np-array using conditional statements also
##### Like we can use all conditional operators for np-arrays it will return an *np-array* with the values of *true or false* with the **shape** of original array

##### ` arr < 5 ` gives returns a boolean array with checking each element with the expression and storing the result in the array

In [59]:
arr_rand_int2 < 5

array([[ True,  True, False, False],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

##### We can also perform the all conditional operators like it `<, >, &, |, !, ~` etc all conditional expressions

##### Here we can use combined conditions like below

In [60]:
(arr_rand_int2 >3) & (arr_rand_int2 < 5)

array([[False,  True, False, False],
       [ True,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

##### `~arr_rand_int2` gives the elemetns with sign change

In [61]:
~arr_rand_int2

array([[ -1,  -5,  -7, -12],
       [ -5,  -5,  -4,  -5],
       [ -6, -10, -11, -15],
       [-10, -12, -15, -16]], dtype=int32)

##### We can use the boolean arrays to get the desired elements from np-array like `arr[arr > 5]`

In [62]:
arr_rand_int2[arr_rand_int2 > 5]

array([ 6, 11,  9, 10, 14,  9, 11, 14, 15], dtype=int32)

In [63]:
arr_rand_int2[(arr_rand_int2 > 3) & (arr_rand_int2 < 5)]

array([4, 4, 4, 4], dtype=int32)

##### We can use any type above for getting elements from the np-array
1. using **Indexing**
2. using **Slicing**
3. using **conditional expressions**

##### Scalar Maths using np

##### `np.add(arr,value)` it adds the value to each and every element in the given array

In [64]:
np.add(arr_rand_int2,4)

array([[ 4,  8, 10, 15],
       [ 8,  8,  7,  8],
       [ 9, 13, 14, 18],
       [13, 15, 18, 19]], dtype=int32)

##### `np.subtract(arr,value)` it subtracts the value to each and every element in the given array

In [65]:
np.subtract(arr_rand_int2,4)

array([[-4,  0,  2,  7],
       [ 0,  0, -1,  0],
       [ 1,  5,  6, 10],
       [ 5,  7, 10, 11]], dtype=int32)

##### Same like we can perform `np.multiply(arr,value)` , `np.divide(arr,value)`, `np.power(arr,value)`

In [66]:
np.multiply(arr_rand_int2,4)

array([[ 0, 16, 24, 44],
       [16, 16, 12, 16],
       [20, 36, 40, 56],
       [36, 44, 56, 60]], dtype=int32)

In [67]:
np.divide(arr_rand_int2,4)

array([[0.  , 1.  , 1.5 , 2.75],
       [1.  , 1.  , 0.75, 1.  ],
       [1.25, 2.25, 2.5 , 3.5 ],
       [2.25, 2.75, 3.5 , 3.75]])

In [68]:
np.power(arr_rand_int2,3)

array([[   0,   64,  216, 1331],
       [  64,   64,   27,   64],
       [ 125,  729, 1000, 2744],
       [ 729, 1331, 2744, 3375]], dtype=int32)

##### Vector Maths

##### Here we can perform vector operations like scalar we have different operations like
1. `np.add(arr1 ,arr2)` - addition of two np-arrays
2. `np.subtract(arr1,arr2)` - subtraction of two np-arrays
3. `np.multiply(arr1,arr2)` - multiplication of two np-arrays
4. `np.divide(arr1,arr2)` - division of two np-arrays
5. `np.power(arr1,arr2)` - power of each element of arr1 with respect to arr2
6. `np.array_equal(arr1,arr2)` - It returns the true if the both arrays have same elements

In [69]:
np.add(arr_rand_int2,arr_rand_int2)

array([[ 0,  8, 12, 22],
       [ 8,  8,  6,  8],
       [10, 18, 20, 28],
       [18, 22, 28, 30]], dtype=int32)

In [70]:
np.subtract(arr_rand_int2,arr_rand_int2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [71]:
np.multiply(arr_rand_int2,arr_rand_int2)

array([[  0,  16,  36, 121],
       [ 16,  16,   9,  16],
       [ 25,  81, 100, 196],
       [ 81, 121, 196, 225]], dtype=int32)

In [76]:
np.divide(arr_rand_int2,arr_rand_int2)

C:\Users\tejva\AppData\Local\Temp\ipykernel_16548\3573279827.py:1: RuntimeWarning: invalid value encountered in divide
  np.divide(arr_rand_int2,arr_rand_int2)


array([[nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [78]:
np.power(arr_rand_int2,arr_rand_int2)

array([[          1,         256,       46656,  1843829075],
       [        256,         256,          27,         256],
       [       3125,   387420489,  1410065408, -1282129920],
       [  387420489,  1843829075, -1282129920,  1500973039]], dtype=int32)

In [79]:
np.array_equal(arr_rand_int2,arr_rand_int2)

True

##### We have some more functions for vector maths using np they are
1. `np.sqrt(arr)` gives sqrt of each element in the np-array
2. `np.sin(arr)` gives sin of each element in the np-array
3. `np.log(arr)` gives log of each element in the np-array
4. `np.abs(arr)` gives abs of each element in the np-array
5. `np.ceil(arr)` gives ceil of each element i the np-array
5. `np.floor(arr)` gives floor of each element i the np-array
5. `np.round(arr)` gives round of each element i the np-array

In [81]:
np.sqrt(arr_rand_int2)

array([[0.        , 2.        , 2.44948974, 3.31662479],
       [2.        , 2.        , 1.73205081, 2.        ],
       [2.23606798, 3.        , 3.16227766, 3.74165739],
       [3.        , 3.31662479, 3.74165739, 3.87298335]])

In [82]:
np.sin(arr_rand_int2)

array([[ 0.        , -0.7568025 , -0.2794155 , -0.99999021],
       [-0.7568025 , -0.7568025 ,  0.14112001, -0.7568025 ],
       [-0.95892427,  0.41211849, -0.54402111,  0.99060736],
       [ 0.41211849, -0.99999021,  0.99060736,  0.65028784]])

In [83]:
np.log(arr_rand_int2)

C:\Users\tejva\AppData\Local\Temp\ipykernel_16548\1487235720.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr_rand_int2)


array([[      -inf, 1.38629436, 1.79175947, 2.39789527],
       [1.38629436, 1.38629436, 1.09861229, 1.38629436],
       [1.60943791, 2.19722458, 2.30258509, 2.63905733],
       [2.19722458, 2.39789527, 2.63905733, 2.7080502 ]])

##### Practice all above and we have some more useful functions like sinh, cos ,cosh -- go with documentation or useful search

### Statistics using Numpy

##### In this We have different functions like `np.mean(arr,axis)` which gives mean of arr along that axis

In [86]:
np.mean(arr_rand_int2,axis=1)

array([ 5.25,  3.75,  9.5 , 12.25])

##### We have some more functions like `np.var(arr)` and `np.std(arr,axis)` which gives variance and standard deviation respectively

##### The np-array itself have some specific functions like `arr.sum()` , `arr.max(axis)`, `arr.min()`, `arr.corrcoef()` which gives sum , max along axis , min, correlation coefficient of np-array

In [87]:
arr_rand_int2.sum()

np.int64(123)

In [88]:
arr_rand_int2.max()

np.int32(15)

In [92]:
np.corrcoef(arr_rand_int2)

array([[ 1.        , -0.10932608,  0.99561764,  0.94619028],
       [-0.10932608,  1.        , -0.09016696, -0.42365927],
       [ 0.99561764, -0.09016696,  1.        ,  0.93317314],
       [ 0.94619028, -0.42365927,  0.93317314,  1.        ]])