## Student Marks Analyzer

##### In this we create a 2-d np-array which represents students as row and subjects as columns

##### Perform actions to calculate
1. Average marks per student
2. Average marks per subject
3. Topper student index
4. Subject with highest average

In [1]:
import numpy as np

In [2]:
student_list = np.array([[85,90,93,74,78],[58,70,63,84,98],[95,80,73,84,98],[75,80,63,94,88],[95,70,83,94,68]])
student_list

array([[85, 90, 93, 74, 78],
       [58, 70, 63, 84, 98],
       [95, 80, 73, 84, 98],
       [75, 80, 63, 94, 88],
       [95, 70, 83, 94, 68]])

In [3]:
np.mean(student_list,axis=1)

array([84. , 74.6, 86. , 80. , 82. ])

In [4]:
np.mean(student_list,axis = 0)

array([81.6, 78. , 75. , 86. , 86. ])

In [5]:
np.argmax(np.sum(student_list,axis = 1))

np.int64(2)

In [6]:
np.argmax(np.mean(student_list,axis=1))

np.int64(2)

In [7]:
student_list.mean(axis=0)

array([81.6, 78. , 75. , 86. , 86. ])

### Project 2 - Sensor Data Simulation

In [8]:
rand_data = np.random.normal(size=(5,5))
rand_data

array([[ 0.45853337,  1.01796655,  0.38908441,  1.30503908, -0.72392823],
       [-0.1177277 ,  1.47179519,  0.72099328, -0.08682964, -0.14527489],
       [-0.2833966 , -0.70093221, -1.18608103,  0.6704003 , -1.46288718],
       [-2.11639875, -1.31448297, -0.04282869, -0.22018177,  0.56681515],
       [-0.71085815,  1.28864803,  0.63337873, -0.70021277,  0.12022642]])

In [9]:
rand_data.mean()

np.float64(-0.04676560385143592)

In [10]:
rand_data.std()

np.float64(0.9059199842087913)

In [11]:
rand_data[rand_data >= 0]

array([0.45853337, 1.01796655, 0.38908441, 1.30503908, 1.47179519,
       0.72099328, 0.6704003 , 0.56681515, 1.28864803, 0.63337873,
       0.12022642])

In [12]:
rand_data +8

array([[8.45853337, 9.01796655, 8.38908441, 9.30503908, 7.27607177],
       [7.8822723 , 9.47179519, 8.72099328, 7.91317036, 7.85472511],
       [7.7166034 , 7.29906779, 6.81391897, 8.6704003 , 6.53711282],
       [5.88360125, 6.68551703, 7.95717131, 7.77981823, 8.56681515],
       [7.28914185, 9.28864803, 8.63337873, 7.29978723, 8.12022642]])

### Project 3 - Image as A Matrix

In [13]:
image = np.random.randint(0,256,(100,100))
image

array([[ 74, 117, 116, ...,  51, 238, 244],
       [183, 152, 146, ..., 199,  50, 169],
       [157, 188,  86, ..., 121,  97,  94],
       ...,
       [105,  56, 158, ...,  99, 144,  85],
       [146, 107, 241, ..., 139,  85, 192],
       [211, 194,  58, ..., 220, 219, 196]], dtype=int32)

In [14]:
image[40:60,40:60]

array([[ 93, 151, 217, 180,  27,  18, 247, 113,  82, 191,  56,  73,   6,
        237, 165, 199, 188, 218,  81,  89],
       [167, 204, 114, 193, 148,  38,  96, 236,  22, 126, 205, 196, 143,
         63, 114,  82,  42, 128, 205, 248],
       [ 59, 196, 209, 134, 157, 247,  72, 169,  14,  20, 185, 242, 127,
        144,  86,  24, 218, 158,  23,  87],
       [186, 111, 206,  36, 226, 119,  95, 224, 145, 201, 229,  63,  88,
         62, 172, 253, 152,  84, 204, 189],
       [171, 212, 173, 217, 239, 162, 194, 112, 120,  62, 245,  49, 198,
        233,  87, 128,  57, 251, 164, 138],
       [176,  34, 102, 148, 222,  15, 200, 202, 204,  62,  41, 182,  76,
        166,  64,  67, 170,  55, 255, 104],
       [209, 172,  51, 141,  97, 105, 166,   3, 144,  89, 162, 182, 219,
        122,  97, 180,  16,  25, 105,   3],
       [ 99,  89, 168,  19,  38,  75,  33,  91, 157, 138, 118,  17,  33,
        107, 224,  36, 161, 137, 179, 193],
       [126,  82,  87, 122,  86,  63, 211, 153,  31, 138, 219, 2

In [15]:
image + 50

array([[124, 167, 166, ..., 101, 288, 294],
       [233, 202, 196, ..., 249, 100, 219],
       [207, 238, 136, ..., 171, 147, 144],
       ...,
       [155, 106, 208, ..., 149, 194, 135],
       [196, 157, 291, ..., 189, 135, 242],
       [261, 244, 108, ..., 270, 269, 246]], dtype=int32)

In [16]:
np.clip(image-50,0,255)

array([[ 24,  67,  66, ...,   1, 188, 194],
       [133, 102,  96, ..., 149,   0, 119],
       [107, 138,  36, ...,  71,  47,  44],
       ...,
       [ 55,   6, 108, ...,  49,  94,  35],
       [ 96,  57, 191, ...,  89,  35, 142],
       [161, 144,   8, ..., 170, 169, 146]], dtype=int32)

In [17]:
image[image > 128] = 255
image

array([[ 74, 117, 116, ...,  51, 255, 255],
       [255, 255, 255, ..., 255,  50, 255],
       [255, 255,  86, ..., 121,  97,  94],
       ...,
       [105,  56, 255, ...,  99, 255,  85],
       [255, 107, 255, ..., 255,  85, 255],
       [255, 255,  58, ..., 255, 255, 255]], dtype=int32)

In [18]:
image[image < 128] = 0
image

array([[  0,   0,   0, ...,   0, 255, 255],
       [255, 255, 255, ..., 255,   0, 255],
       [255, 255,   0, ...,   0,   0,   0],
       ...,
       [  0,   0, 255, ...,   0, 255,   0],
       [255,   0, 255, ..., 255,   0, 255],
       [255, 255,   0, ..., 255, 255, 255]], dtype=int32)

##### `np.where(arr,if_true,if_false)` is used instead of boolean indexing manually

##### Here we are increasing the value to maximum for the ones which is higher than 128

In [19]:
np.where(image > 128,255,0)

array([[  0,   0,   0, ...,   0, 255, 255],
       [255, 255, 255, ..., 255,   0, 255],
       [255, 255,   0, ...,   0,   0,   0],
       ...,
       [  0,   0, 255, ...,   0, 255,   0],
       [255,   0, 255, ..., 255,   0, 255],
       [255, 255,   0, ..., 255, 255, 255]])

##### To Invert the image use this syntax

In [20]:
255 - image

array([[255, 255, 255, ..., 255,   0,   0],
       [  0,   0,   0, ...,   0, 255,   0],
       [  0,   0, 255, ..., 255, 255, 255],
       ...,
       [255, 255,   0, ..., 255,   0, 255],
       [  0, 255,   0, ...,   0, 255,   0],
       [  0,   0, 255, ...,   0,   0,   0]], dtype=int32)

##### To flip the image use the below syntax

In [21]:
image[::,::-1]

array([[255, 255,   0, ...,   0,   0,   0],
       [255,   0, 255, ..., 255, 255, 255],
       [  0,   0,   0, ...,   0, 255, 255],
       ...,
       [  0, 255,   0, ..., 255,   0,   0],
       [255,   0, 255, ..., 255,   0, 255],
       [255, 255, 255, ...,   0, 255, 255]], dtype=int32)

### Project 4 - Data Normalization

In [22]:
data = np.random.normal(size=(5,5))
data

array([[-0.10663354, -0.69351571,  0.29632873, -0.81373924, -0.61107629],
       [-0.3459972 ,  1.49660246, -0.53243995,  0.32823917,  0.32140753],
       [-0.76206071,  0.55933118,  0.88979451,  1.33671249,  0.27409261],
       [-1.56523694, -0.33942238, -0.67953015,  1.22820643,  2.46175879],
       [ 0.49362639,  0.1268997 ,  2.57425244,  0.85949745, -0.94003807]])

In [26]:
data_max = data.max()
data_min = data.min()
data_min,data_max

(np.float64(-1.5652369417827454), np.float64(2.5742524431243723))

In [25]:
(data - data_min)/(data_max+data_min)

array([[1.44557086, 0.86393244, 1.84493268, 0.74478311, 0.94563527],
       [1.2083459 , 3.03448203, 1.02356901, 1.876558  , 1.8697874 ],
       [0.79599989, 2.10558521, 2.43309587, 2.87602067, 1.82289523],
       [0.        , 1.21486197, 0.87779305, 2.7684841 , 3.99101474],
       [2.0404675 , 1.67701749, 4.10250326, 2.40306951, 0.61961275]])

In [29]:
data_std = data.std()
data_mean = data.mean()

In [30]:
(data - data_mean)/data_std

array([[-0.33591784, -0.91419586,  0.06113669, -1.03265682, -0.83296507],
       [-0.57177224,  1.24381349, -0.75548159,  0.0925793 ,  0.08584782],
       [-0.98173594,  0.32028332,  0.64590181,  1.08626763,  0.03922657],
       [-1.77313698, -0.56529381, -0.90041534,  0.97935235,  2.19481988],
       [ 0.25554182, -0.10580838,  2.30566428,  0.61604893, -1.15710401]])