# Importing numpy as np


In [1]:
import numpy as np

### creating numpy array


In [3]:
arr_one = np.array([1,2,3,4,5,6])
arr_one

array([1, 2, 3, 4, 5, 6])

### creating two dimension array


In [4]:
arr_two= np.array([[1,2,3,4],[5,6,7,8]])
arr_two

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### creating numpy arrays with all zeros filled using `np.zeros`

In [5]:
arr_zero = np.zeros(5)
arr_zero

array([0., 0., 0., 0., 0.])

### creating numpy arrays with all ones filled using `np.ones`


In [6]:
arr_ones = np.ones(5)
arr_ones

array([1., 1., 1., 1., 1.])

#### we can use `np.zeros` and `np.ones` functions by passing shape of the array needed

In [7]:
arr_zeros_1 = np.zeros((3,4))
arr_ones_1 = np.ones((3,4))
arr_zeros_1, arr_ones_1

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

##### here these `np.zeros` and `np.ones` gives arrays in np.float data type
##### you can check the data type using `arr.dtype` where arr is the `np.array` or np object

In [9]:
arr_zeros_1.dtype,arr_ones_1.dtype

(dtype('float64'), dtype('float64'))

#### here we learn some basic numpy properties 
1.to see *size* of the numpy-array use `arr.size`

2.to see *shape* of the nu,py-array use `arr.shape`

3.to see *documentation* of any function in numpy library use `np.info`

4.to *convert* the numpy-array into python lists use `arr.tolist()`

5.to *convert* the type of numpy-arrray use `arr.astype(*dtype*)`

In [10]:
arr_two.size

8

In [11]:
arr_two.shape

(2, 4)

In [17]:
np.info(np.dtypes)

This module is home to specific dtypes related functionality and their classes.
For more general information about dtypes, also see `numpy.dtype` and
:ref:`arrays.dtypes`.

Similar to the builtin ``types`` module, this submodule defines types (classes)
that are not widely used directly.

.. versionadded:: NumPy 1.25

    The dtypes module is new in NumPy 1.25.  Previously DType classes were
    only accessible indirectly.


DType classes
-------------

The following are the classes of the corresponding NumPy dtype instances and
NumPy scalar types.  The classes can be used in ``isinstance`` checks and can
also be instantiated or used directly.  Direct use of these classes is not
typical, since their scalar counterparts (e.g. ``np.float64``) or strings
like ``"float64"`` can be used.


In [13]:
li = arr_two.tolist()
li

[[1, 2, 3, 4], [5, 6, 7, 8]]

##### now we check the `arr_two` dtype and convert it into float

In [14]:
arr_two.dtype

dtype('int64')

##### here the astype returns an numpy-array but it will not store the object itself

In [19]:
arr_two.astype(np.float64)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

##### only while using the astype it will give the array else the same data type will be there

In [20]:
arr_two.dtype

dtype('int64')

##### now let us look for another function same like `zeros`,`ones` that is `np.eye`

it gives an identity matrix that is it will give an n x n matrix with 1 on diagonals and 0 on other places


In [21]:
arr_eye = np.eye(5)
arr_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##### another function to create np-array is using `np.linspace` this creates the array from start to stop on giving divison length between them

In [22]:
arr_linspace = np.linspace(3,30,10)
arr_linspace

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

##### here the array dtype is `np.float64`

In [23]:
arr_linspace.dtype

dtype('float64')

##### Now another function to create numpy-array is `np.arange` it creates a range of values with a *start* , *stop* , *step* in it

In [27]:
arr_arange = np.arange(16,32)
arr_arange

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

##### the `np.arange` array shape is always 1-dim.

In [31]:
arr_arange.shape

(16,)

##### another function for creating np-arrays is `np.full` it can take the shape that needed to create and a value to fill the entire array with that

In [33]:
arr_full = np.full((3,4),5)
arr_full

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

##### another type to create a np-array is to use `np.random.rand`  
1. we can use it two type if we use `np.random.rand` directly it gives valuse in range between 0 and 1
2. if we use `np.random.rand()*100` it gives float between 0 and 100 

In [35]:
arr_rand = np.random.rand(3,4)
arr_rand

array([[0.23199509, 0.67837084, 0.04804761, 0.24303748],
       [0.08348954, 0.43906233, 0.90825989, 0.76213006],
       [0.67037347, 0.08284042, 0.01615968, 0.64255552]])

In [40]:
arr_rand_1 = np.random.rand(3,4)*100
arr_rand_1

array([[14.27204893, 58.30458727,  8.9981414 , 48.31574177],
       [34.9973212 , 52.24385162, 31.06756376, 87.87397724],
       [36.06176444, 42.50517046,  2.08876395, 84.03329605]])

##### the last function is `np.random.randint` which takes an integer number and a tuple of shape and it returns a random integer between given starting and stoping integer


In [42]:
arr_rand_int = np.random.randint(10,size=(3,4))
arr_rand_int

array([[6, 7, 4, 6],
       [2, 8, 1, 4],
       [6, 3, 4, 5]], dtype=int32)

##### Now let us see all listed np-array creation functions
1. `np.array`
2. `np.zeros`
3. `np.ones`
4. `np.eye`
5. `np.linspace`
6. `np.arange`
7. `np.full`
8. `np.random.rand`
9. `np.random.randint`