# Importing numpy as np
#### As we always wanted to call the module again and again we can call it simple as np instead of numpy

In [1]:
import numpy as np

##### creating numpy array using `np.array()`

In [2]:
arr_one = np.array([1,2,3,4,5,6])
arr_one

array([1, 2, 3, 4, 5, 6])

##### creating two dimension array


In [3]:
arr_two= np.array([[1,2,3,4],[5,6,7,8]])
arr_two

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##### Here we can see the difference between numpy array and python lists

In [4]:
list1 = list(range(1000000))

In [5]:
list2 = np.arange(1000000)

In [6]:
%time for _ in range(10):list2_1 = list2 * 2

CPU times: total: 78.1 ms
Wall time: 77 ms


In [7]:
%time for _ in range(10):list1_1 = [x*2 for x in list1]

CPU times: total: 1.06 s
Wall time: 1.07 s


##### creating numpy arrays with all zeros filled using `np.zeros`

In [8]:
arr_zero = np.zeros(5)
arr_zero

array([0., 0., 0., 0., 0.])

##### creating numpy arrays with all ones filled using `np.ones`


In [9]:
arr_ones = np.ones(5)
arr_ones

array([1., 1., 1., 1., 1.])

##### we can use `np.zeros` and `np.ones` functions by passing shape of the array needed

In [10]:
arr_zeros_1 = np.zeros((3,4))
arr_ones_1 = np.ones((3,4))
arr_zeros_1, arr_ones_1

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

##### here these `np.zeros` and `np.ones` gives arrays in np.float data type
##### you can check the data type using `arr.dtype` where arr is the `np.array` or np object

In [11]:
arr_zeros_1.dtype,arr_ones_1.dtype

(dtype('float64'), dtype('float64'))

#### here we learn some basic numpy properties 
1. to see *size* of the numpy-array use `arr.size`

2. to see *shape* of the nu,py-array use `arr.shape`

3. to see *documentation* of any function in numpy library use `np.info`

4. to *convert* the numpy-array into python lists use `arr.tolist()`

5. to *convert* the type of numpy-arrray use `arr.astype(*dtype*)`

In [12]:
arr_two.size

8

In [13]:
arr_two.shape

(2, 4)

In [14]:
np.info(np.dtypes)

This module is home to specific dtypes related functionality and their classes.
For more general information about dtypes, also see `numpy.dtype` and
:ref:`arrays.dtypes`.

Similar to the builtin ``types`` module, this submodule defines types (classes)
that are not widely used directly.

.. versionadded:: NumPy 1.25

    The dtypes module is new in NumPy 1.25.  Previously DType classes were
    only accessible indirectly.


DType classes
-------------

The following are the classes of the corresponding NumPy dtype instances and
NumPy scalar types.  The classes can be used in ``isinstance`` checks and can
also be instantiated or used directly.  Direct use of these classes is not
typical, since their scalar counterparts (e.g. ``np.float64``) or strings
like ``"float64"`` can be used.


In [15]:
li = arr_two.tolist()
li

[[1, 2, 3, 4], [5, 6, 7, 8]]

##### now we check the `arr_two` dtype and convert it into float

In [16]:
arr_two.dtype

dtype('int64')

##### here the astype returns an numpy-array but it will not store the object itself

In [17]:
arr_two.astype(np.float64)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

##### only while using the astype it will give the array else the same data type will be there

In [18]:
arr_two.dtype

dtype('int64')

##### now let us look for another function same like `zeros`,`ones` that is `np.eye`

it gives an identity matrix that is it will give an n x n matrix with 1 on diagonals and 0 on other places


In [19]:
arr_eye = np.eye(5)
arr_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##### another function to create np-array is using `np.linspace` this creates the array from start to stop on giving divison length between them

In [20]:
arr_linspace = np.linspace(3,30,10)
arr_linspace

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

##### here the array dtype is `np.float64`

In [21]:
arr_linspace.dtype

dtype('float64')

##### Now another function to create numpy-array is `np.arange` it creates a range of values with a *start* , *stop* , *step* in it

In [22]:
arr_arange = np.arange(16,32)
arr_arange

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

##### the `np.arange` array shape is always 1-dim.

In [23]:
arr_arange.shape

(16,)

##### another function for creating np-arrays is `np.full` it can take the shape that needed to create and a value to fill the entire array with that

In [24]:
arr_full = np.full((3,4),5)
arr_full

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

##### another type to create a np-array is to use `np.random.rand`  
1. we can use it two type if we use `np.random.rand` directly it gives valuse in range between 0 and 1
2. if we use `np.random.rand()*100` it gives float between 0 and 100 

In [25]:
arr_rand = np.random.rand(3,4)
arr_rand

array([[0.24739767, 0.48361105, 0.82001805, 0.94184005],
       [0.37278519, 0.17693066, 0.50358853, 0.07924663],
       [0.6914479 , 0.70834748, 0.64030182, 0.43031932]])

In [26]:
arr_rand_1 = np.random.rand(3,4)*100
arr_rand_1

array([[67.23912801, 66.40889328, 63.35785071, 53.83022153],
       [41.43071805, 69.36935344, 84.60372133, 29.79592424],
       [96.94503403, 13.76894296, 96.81406368, 58.70881047]])

##### the last function is `np.random.randint` which takes an integer number and a tuple of shape and it returns a random integer between given starting and stoping integer


In [27]:
arr_rand_int = np.random.randint(10,size=(3,4))
arr_rand_int

array([[5, 6, 3, 9],
       [2, 6, 1, 2],
       [9, 4, 3, 1]], dtype=int32)

##### Now let us see all listed np-array creation functions
1. `np.array`
2. `np.zeros`
3. `np.ones`
4. `np.eye`
5. `np.linspace`
6. `np.arange`
7. `np.full`
8. `np.random.rand`
9. `np.random.randint`

### Copying, sorting, & Reshaping


##### To copy the np-array we use `np.copy(arr)` function which copy the array into new memory

In [28]:
arr_two_copy = np.copy(arr_two)
arr_two_copy

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##### `np.copy(arr)` makes deep copy so any change in *arr* do not **replicate** in copied array

In [29]:
arr_two_copy[1,2] = 6
arr_two_copy

array([[1, 2, 3, 4],
       [5, 6, 6, 8]])

In [30]:
arr_two

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##### we can create a view for the given arr with different **dtype** using `arr.view(dtype)` or else we can leave empty to get same data type view

In [31]:
arr_two_view = arr_two.view()# use np.float64 as parameter to get difference
arr_two_view

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##### View can change values if the *original array* values are changed or **vice-verca**

In [32]:
arr_two_view[1,2] = 6
arr_two_view

array([[1, 2, 3, 4],
       [5, 6, 6, 8]])

In [33]:
arr_two

array([[1, 2, 3, 4],
       [5, 6, 6, 8]])

In [34]:
arr_two[1,2] = 7
arr_two

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
arr_two_view

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##### To sort an np-array we can use the np-array function *i.e* `arr.sort()`

In [36]:
arr_rand_int2 = np.random.randint(16,size=(4,4))
arr_rand_int2

array([[13, 14,  9,  3],
       [ 9, 11, 10, 12],
       [ 1, 13, 11, 15],
       [ 4, 15,  0,  5]], dtype=int32)

##### As this `arr_rand_int2` is not **1-D** array but it does sort the array for only one row means all elements in one row is sorted in the same row 

In [37]:
arr_rand_int2.sort()
arr_rand_int2

array([[ 3,  9, 13, 14],
       [ 9, 10, 11, 12],
       [ 1, 11, 13, 15],
       [ 0,  4,  5, 15]], dtype=int32)

##### Here we can also use parameter `arr.sort(axis)` where *axis = 0 or 1* 
1. axis = 0 represent to sort the values according to column wise means it sort all the column values
2. axis = 1 represent to sort the values according to row wise means it sort all the values in row

`arr.sort()` corresponds to `arr.sort(axis=1)`

In [38]:
arr_rand_int2.sort(axis=0)
arr_rand_int2

array([[ 0,  4,  5, 12],
       [ 1,  9, 11, 14],
       [ 3, 10, 13, 15],
       [ 9, 11, 13, 15]], dtype=int32)

##### To flatten an n-dim or any-shape np-array we use `arr.flatten()` it converts into 1-dim np.array and returns an 1-dim np.array

In [39]:
arr_rand_int2.flatten()

array([ 0,  4,  5, 12,  1,  9, 11, 14,  3, 10, 13, 15,  9, 11, 13, 15],
      dtype=int32)

##### To **Transpose** the np-arr i.e *rows* becoming *columns* and vice-verca we use `arr.T`

In [40]:
arr_rand_int2,arr_rand_int2.T

(array([[ 0,  4,  5, 12],
        [ 1,  9, 11, 14],
        [ 3, 10, 13, 15],
        [ 9, 11, 13, 15]], dtype=int32),
 array([[ 0,  1,  3,  9],
        [ 4,  9, 10, 11],
        [ 5, 11, 13, 13],
        [12, 14, 15, 15]], dtype=int32))

##### Reshaping an array using `arr.reshape(x,y)` that reshapes an array into x,y shape
Make sure to have **x*y** elements in the array to reshape correctly without any error

In [41]:
arr_rand_int2.reshape(2,8,order='F')

array([[ 0,  3,  4, 10,  5, 13, 12, 15],
       [ 1,  9,  9, 11, 11, 13, 14, 15]], dtype=int32)

##### Here we have two orders they are `'C'` and `'F'` 
`C` makes to reshape on the basis of row wise filling elements

`F` makes to reshape on the basis of column wise filling elements

##### Here `arr_rand_int2` is of shape **(4,4)** but after reshape you can see the output in shape of **(2,8)**

##### Now we get another np-array function that is `arr.resize((x,y))` this make an array to rershape to any size and it automatically fills the values to **0** that are not initialised

In [42]:
arr_arange.resize((2,8))
arr_arange

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

#### Adding & Removing Elements

##### To append the value to the end of np-array we use `np.append(arr,values)` 

In [43]:
arr_append = np.append(arr_one,[1,2,3,5])
arr_append

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 5])

##### To insert values in np-array we use `np.insert(arr,pos,values)`

In [44]:
arr_insert = np.insert(arr_two,1,[1,5,3,4],axis = 0)
arr_insert

array([[1, 2, 3, 4],
       [1, 5, 3, 4],
       [5, 6, 7, 8]])

##### To delete values in np-array we use `np.delete(arr,pos,axis)`

In [45]:
arr_delete = np.delete(arr_two,0,axis=0)
arr_delete

array([[5, 6, 7, 8]])

In [46]:
arr_delete = np.delete(arr_two,1,axis=1)
arr_delete

array([[1, 3, 4],
       [5, 7, 8]])

#### Combining and Splitting
##### to concatenate two np-arrays we use `np.concatenate((arr1,arr2),axis)`

In [47]:
arr_concatenate = np.concatenate((arr_rand_int2,arr_two),axis=0)
arr_concatenate

array([[ 0,  4,  5, 12],
       [ 1,  9, 11, 14],
       [ 3, 10, 13, 15],
       [ 9, 11, 13, 15],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [48]:
arr_concatenate = np.concatenate((arr_two,arr_two),axis=1)
arr_concatenate

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

##### To split an array we use `np.split(arr,value)` here value refers to how many array it needs to be split

In [49]:
arr_split = np.split(arr_rand_int2,4)
arr_split

[array([[ 0,  4,  5, 12]], dtype=int32),
 array([[ 1,  9, 11, 14]], dtype=int32),
 array([[ 3, 10, 13, 15]], dtype=int32),
 array([[ 9, 11, 13, 15]], dtype=int32)]

##### To Split np-array Horizontally we use `np.hsplit(arr,value)` it splits the arr horizontally

In [50]:
arr_hsplit = np.hsplit(arr_rand_int2,4)
arr_hsplit

[array([[0],
        [1],
        [3],
        [9]], dtype=int32),
 array([[ 4],
        [ 9],
        [10],
        [11]], dtype=int32),
 array([[ 5],
        [11],
        [13],
        [13]], dtype=int32),
 array([[12],
        [14],
        [15],
        [15]], dtype=int32)]

### Indexing & Slicing

##### Indexing with `[]` to get elements of the np-array

##### `arr[1]` gives element at position 1 respecting to shape of the np-arr

In [53]:
arr_rand_int2[1]

array([ 1,  9, 11, 14], dtype=int32)

##### `arr[1,2]` gives element of position `arr[1][2]` 

In [52]:
arr_rand_int2[1,2]

np.int32(11)

##### We can assign the values using `[]` like `arr[1] = 4 `

In [55]:
arr_rand_int2[1] = 4
arr_rand_int2

array([[ 0,  4,  5, 12],
       [ 4,  4,  4,  4],
       [ 3, 10, 13, 15],
       [ 9, 11, 13, 15]], dtype=int32)

##### Here something called broadcasting is applied in the above code. Broadcasting means some times the given number like above we give `4` value for `arr_rand_int2[1]` but it has 